name: my first manual workflow

on: workflow_dispatch

jobs:
  build_on_ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Run a multi-line script
        run: |
          echo "hello world"
          date

  build_on_windows:
    runs-on: windows-latest
    steps:
      - name: run multi-line script
        run: |
          each "Hello Windows"
          Get-Date
